In [1]:
##################################################################################################################3333
#
#                         COURSE: 2
#                         Course Name: Machine Learning for Predictive Problems
#                         Student Name: Jyothi Nandikonda
#                         Dataset: Winedata
#                         Homework: 3
#                         Due Date: 16.11.18
#
##########################################################################################################################3

In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter("ignore")

In [3]:
df_white_wine = pd.read_csv('winequality-white.csv', sep=';')

In [4]:
df_red_wine = pd.read_csv('winequality-red.csv', sep=';')

In [5]:
df_red_wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [6]:
df_white_wine["wine_type"] = 0
df_red_wine["wine_type"] = 1

In [7]:
len(df_white_wine)

4898

In [8]:
len(df_red_wine)

1599

In [9]:
df = pd.concat([df_red_wine, df_white_wine], ignore_index=True, sort=True)

In [10]:
df.head()

alcohol  chlorides  citric acid  density  fixed acidity  \
0      9.4      0.076         0.00   0.9978            7.4   
1      9.8      0.098         0.00   0.9968            7.8   
2      9.8      0.092         0.04   0.9970            7.8   
3      9.8      0.075         0.56   0.9980           11.2   
4      9.4      0.076         0.00   0.9978            7.4   

   free sulfur dioxide    pH  quality  residual sugar  sulphates  \
0                 11.0  3.51        5             1.9       0.56   
1                 25.0  3.20        5             2.6       0.68   
2                 15.0  3.26        5             2.3       0.65   
3                 17.0  3.16        6             1.9       0.58   
4                 11.0  3.51        5             1.9       0.56   

   total sulfur dioxide  volatile acidity  wine_type  
0                  34.0              0.70          1  
1                  67.0              0.88          1  
2                  54.0              0.76          1  
3                  60.0              0.28          1  
4                  34.0              0.70          1

In [11]:
df.tail()

alcohol  chlorides  citric acid  density  fixed acidity  \
6492     11.2      0.039         0.29  0.99114            6.2   
6493      9.6      0.047         0.36  0.99490            6.6   
6494      9.4      0.041         0.19  0.99254            6.5   
6495     12.8      0.022         0.30  0.98869            5.5   
6496     11.8      0.020         0.38  0.98941            6.0   

      free sulfur dioxide    pH  quality  residual sugar  sulphates  \
6492                 24.0  3.27        6             1.6       0.50   
6493                 57.0  3.15        5             8.0       0.46   
6494                 30.0  2.99        6             1.2       0.46   
6495                 20.0  3.34        7             1.1       0.38   
6496                 22.0  3.26        6             0.8       0.32   

      total sulfur dioxide  volatile acidity  wine_type  
6492                  92.0              0.21          0  
6493                 168.0              0.32          0  
6494                 111.0              0.24          0  
6495                 110.0              0.29          0  
6496                  98.0              0.21          0

In [12]:
len(df)

6497

In [13]:
from sklearn.utils import shuffle
df = shuffle(df)

In [14]:
df.head()

alcohol  chlorides  citric acid  density  fixed acidity  \
2340     11.0      0.031         0.30  0.99115            5.8   
264      10.9      0.064         0.49  0.99990           12.5   
2761     10.2      0.043         0.41  0.99460            6.6   
3896      9.5      0.042         0.42  0.99674            6.5   
2609     10.3      0.043         0.44  0.99320            7.6   

      free sulfur dioxide    pH  quality  residual sugar  sulphates  \
2340                 21.0  3.44        6             1.5       0.55   
264                   5.0  3.08        5             2.4       0.87   
2761                 29.0  3.15        7             7.4       0.60   
3896                 66.0  3.24        6            10.6       0.53   
2609                 25.0  3.11        6             1.4       0.75   

      total sulfur dioxide  volatile acidity  wine_type  
2340                  57.0              0.20          0  
264                   27.0              0.56          1  
2761                 151.0              0.25          0  
3896                 202.0              0.29          0  
2609                 109.0              0.16          0

In [15]:
df.reset_index(drop=True, inplace=True)

In [16]:
df.dropna()

alcohol  chlorides  citric acid  density  fixed acidity  \
0     11.000000      0.031         0.30  0.99115            5.8   
1     10.900000      0.064         0.49  0.99990           12.5   
2     10.200000      0.043         0.41  0.99460            6.6   
3      9.500000      0.042         0.42  0.99674            6.5   
4     10.300000      0.043         0.44  0.99320            7.6   
5      8.700000      0.056         0.40  0.99670            7.9   
6     11.500000      0.121         0.66  0.99780           11.6   
7      9.400000      0.464         0.70  0.99740            7.8   
8      9.600000      0.097         0.21  0.99880            9.2   
9      9.500000      0.032         0.16  0.99274            6.3   
10     8.800000      0.053         0.44  1.00060            8.1   
11    10.500000      0.029         0.50  0.99428            5.6   
12     9.000000      0.038         0.39  0.99990            7.2   
13     9.400000      0.172         0.39  0.99370            6.7   
14    11.400000      0.037         0.37  0.99020            7.6   
15    10.700000      0.063         0.35  0.99184            7.0   
16    12.700000      0.021         0.32  0.98890            6.7   
17     9.300000      0.048         0.37  0.99380            7.5   
18    11.300000      0.039         0.27  0.99360            6.9   
19     8.900000      0.048         0.35  0.99750            6.1   
20    12.300000      0.042         0.26  0.99067            6.5   
21    11.200000      0.057         0.42  0.99400            7.9   
22     9.100000      0.042         0.30  0.99540            9.4   
23    11.300000      0.038         0.24  0.99139            5.9   
24     9.900000      0.080         0.26  0.99584            7.3   
25    10.800000      0.043         0.33  0.99118            7.0   
26    11.400000      0.041         0.42  0.99250            8.6   
27    11.000000      0.036         0.32  0.99096            6.2   
28     9.533333      0.050         0.20  0.99504            6.5   
29     9.200000      0.074         0.32  0.99800            7.1   
...         ...        ...          ...      ...            ...   
6467   9.500000      0.045         0.32  1.00000            6.5   
6468  12.800000      0.030         0.29  0.99110            8.2   
6469  10.000000      0.039         0.23  0.99243            5.5   
6470  11.200000      0.040         0.26  0.99194            7.3   
6471   9.500000      0.066         0.02  0.99720            7.0   
6472  10.300000      0.039         0.34  0.99590            7.8   
6473  11.200000      0.048         0.21  0.99138            5.7   
6474  11.200000      0.045         0.34  0.99132            7.1   
6475  12.800000      0.047         0.40  0.99000            6.8   
6476  12.300000      0.021         0.33  0.99021            7.0   
6477  11.900000      0.026         0.27  0.98994            5.8   
6478   9.500000      0.067         0.02  0.99700            6.4   
6479   9.400000      0.075         0.00  0.99780            7.4   
6480  11.200000      0.045         0.28  0.99130            5.7   
6481   9.300000      0.097         0.26  0.99760            8.7   
6482  11.000000      0.034         0.36  0.99074            6.3   
6483   8.700000      0.085         0.25  1.00044            7.2   
6484   9.800000      0.050         0.25  0.99840            7.6   
6485  12.100000      0.040         0.34  0.99111            6.5   
6486   9.500000      0.080         0.00  0.99760            8.0   
6487   9.000000      0.051         0.30  0.99835            6.6   
6488  11.300000      0.062         0.32  0.99470            7.2   
6489   9.200000      0.038         0.05  0.99240            5.8   
6490   8.900000      0.070         0.30  0.99666            6.7   
6491  10.600000      0.031         0.24  0.99397            7.5   
6492  11.600000      0.045         0.32  0.99350            7.0   
6493  10.200000      0.040         0.38  0.99320            8.6   
6494  12.700000      0.049         0.37  0.99007       

In [17]:
df.tail()

alcohol  chlorides  citric acid  density  fixed acidity  \
6492     11.6      0.045         0.32  0.99350            7.0   
6493     10.2      0.040         0.38  0.99320            8.6   
6494     12.7      0.049         0.37  0.99007            8.0   
6495      9.8      0.102         0.07  1.00015            9.9   
6496     10.6      0.047         0.49  0.99252            7.7   

      free sulfur dioxide    pH  quality  residual sugar  sulphates  \
6492                 35.0  3.09        8            10.5       0.33   
6493                 41.0  2.95        6             3.4       0.39   
6494                 36.0  2.89        6             0.9       0.44   
6495                 32.0  3.31        5             3.4       0.71   
6496                 31.0  3.07        6             2.5       0.57   

      total sulfur dioxide  volatile acidity  wine_type  
6492                 135.0              0.36          0  
6493                 143.0              0.16          0  
6494                 109.0              0.18          1  
6495                  71.0              0.59          1  
6496                 169.0              0.25          0

# Using regression to predict the alcohol level of the wine.

Prepring dependent and independent variables for regression

In [18]:
X = np.array(df.drop(columns=['alcohol'])) # Feature: Train data

In [19]:
y = np.array(df.alcohol) # Target: test data

In [20]:
y = y.reshape(-1, 1)

In [21]:
from sklearn import preprocessing

In [22]:
scaler = preprocessing.StandardScaler().fit(y)

In [23]:
X = scaler.transform(X)
y = scaler.transform(y)

In [25]:
y

array([[ 0.42611996],
       [ 0.34227095],
       [-0.2446721 ],
       ...,
       [ 1.85155309],
       [-0.58006813],
       [ 0.09072393]])

# Split the Dataset into Train and Test (75 to train and 25 to test)

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [28]:
len(X_train) #Train data

4872

In [29]:
len(X_test) #Test Data

1625

# Model:Linear Regression

In [30]:
from sklearn.linear_model import LinearRegression


In [30]:

linear = LinearRegression()
linear.fit(X_train, y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [31]:
linear.score(X_test, y_test)

0.8528852557683432

In [32]:
prediction = linear.predict(X_test)

In [33]:
#First 5 predictions
prediction[: 5]

array([[-0.63296654],
       [ 0.65071892],
       [ 1.27559558],
       [ 0.72957075],
       [ 1.52245281]])

In [34]:
#Actual values
y_test[: 5]

array([[0.00687492],
       [0.50996897],
       [1.51615706],
       [0.42611996],
       [1.51615706]])

In [35]:
y_test_inv = scaler.inverse_transform(y_test)
prediction_inv = scaler.inverse_transform(prediction)

In [36]:
#First 5 predicted alcohol levels
prediction_inv[: 5]

array([[ 9.7369123 ],
       [11.2678612 ],
       [12.01310158],
       [11.36190147],
       [12.30750843]])

In [37]:
#First 5 actual alcohol levels
y_test_inv[: 5]

array([[10.5],
       [11.1],
       [12.3],
       [11. ],
       [12.3]])

# Binary classification to predict the type of wine.

In [31]:
from sklearn.utils import shuffle
df = shuffle(df)

In [32]:
df.reset_index(drop=True, inplace=True)

In [33]:
df.head()

alcohol  chlorides  citric acid  density  fixed acidity  \
0      9.2      0.052         0.48  0.99782            6.1   
1     11.4      0.046         0.51  0.99300            8.3   
2     11.7      0.030         0.28  0.99062            5.7   
3     12.3      0.059         0.03  0.99520            6.6   
4     11.3      0.043         0.22  0.99238            5.0   

   free sulfur dioxide    pH  quality  residual sugar  sulphates  \
0                 25.0  3.07        6            15.8       0.45   
1                 11.0  3.02        5             2.0       0.55   
2                 22.0  3.31        7             4.1       0.38   
3                 32.0  3.52        7             2.3       0.56   
4                 46.0  3.75        6             2.7       0.76   

   total sulfur dioxide  volatile acidity  wine_type  
0                  94.0             0.250          0  
1                 207.0             0.410          0  
2                  86.0             0.310          0  
3                  48.0             0.840          1  
4                 153.0             0.255          0

In [34]:
X = np.array(df.drop(columns=['wine_type']))

In [35]:
y = np.array(df.wine_type)

In [36]:
y

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [37]:
y = y.reshape(-1,1)

In [38]:
y # It has to be one dimensional vector

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]], dtype=int64)

In [39]:
from sklearn import preprocessing

In [40]:
scaler = preprocessing.StandardScaler().fit(y)

In [41]:
X = scaler.transform(X)

In [42]:
y

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]], dtype=int64)

In [50]:
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [44]:
X_train

array([[ 2.05547969e+01, -3.29924721e-01,  9.02251806e-03, ...,
         7.51920576e-01,  2.08368712e+02,  4.03687111e-01],
       [ 2.17155751e+01, -4.64574994e-01,  4.96549368e-01, ...,
         9.84076219e-01,  3.01230969e+02, -1.99917561e-01],
       [ 2.14834195e+01, -4.08857639e-01, -1.53486432e-01, ...,
         1.12336960e+00,  6.44322134e+01,  6.12627190e-01],
       ...,
       [ 2.03226413e+01, -4.25108534e-01,  5.19764933e-01, ...,
         7.28705011e-01,  4.01057896e+02,  1.71531468e-01],
       [ 2.17155751e+01, -4.64574994e-01,  3.80471547e-01, ...,
         6.12627190e-01,  3.96414783e+02,  1.01884775e-01],
       [ 2.82159331e+01, -4.83147445e-01, -5.71366589e-01, ...,
         4.96549368e-01,  2.57121397e+02,  3.22380824e-02]])

In [45]:
from sklearn import svm

In [46]:
clf = svm.SVC()

In [47]:
clf.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [56]:
clf.score(X_test, y_test)

0.8892307692307693

In [57]:
prediction = clf.predict(X_test)

In [58]:
prediction[: 10]

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 1], dtype=int64)

In [59]:
actual_set = y_test

In [60]:
actual_set[: 10]

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1]], dtype=int64)

# Multiclass classification to predict the quality of the wine.

In [51]:
from sklearn.utils import shuffle
df = shuffle(df)

In [52]:
df.reset_index(drop=True, inplace=True)

In [53]:
df.shape

(6497, 13)

In [54]:
X = np.array(df.drop(columns=['quality']))

In [55]:
y = np.array(df.quality)

In [56]:
np.unique(df.quality)

array([3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [57]:
le = preprocessing.LabelEncoder()

In [58]:
le.fit_transform(y)

array([2, 3, 3, ..., 3, 3, 3], dtype=int64)

In [59]:
np.unique(y)

array([3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [60]:
y = y.reshape(-1, 1)

In [61]:
y

array([[5],
       [6],
       [6],
       ...,
       [6],
       [6],
       [6]], dtype=int64)

In [72]:
scaler_multiclass = preprocessing.StandardScaler().fit(y)

In [73]:
X = scaler_multiclass.transform(X)

In [74]:
X

array([[  5.01795944,  -6.61298287,  -6.34270891, ..., 135.34498134,
         -6.31980433,  -6.66337293],
       [  3.52916217,  -6.62099947,  -5.89606973, ..., 183.4445852 ,
         -6.33125662,  -6.66337293],
       [  7.65198536,  -6.62328993,  -6.35416119, ...,  84.95492015,
         -6.14802003,  -6.66337293],
       ...,
       [  5.70509663,  -6.63474221,  -6.23963833, ..., 120.45700871,
         -6.46868406,  -6.66337293],
       [  5.36152803,  -6.56259281,  -6.65192064, ...,  13.95074301,
         -5.99914031,  -5.51814427],
       [  4.21629937,  -6.60038536,  -6.23963833, ..., 213.22053045,
         -6.35416119,  -6.66337293]])

In [75]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [76]:
clf = svm.SVC()

In [77]:
clf.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [78]:
clf.score(X_test, y_test)

0.571076923076923

In [79]:
forecast_set = clf.predict(X_test)

In [80]:
forecast_set[: 10].reshape(-1, 1)

array([[5],
       [6],
       [7],
       [6],
       [5],
       [7],
       [6],
       [6],
       [5],
       [6]], dtype=int64)

In [81]:
actual_set = y_test

In [82]:
actual_set[: 10]

array([[5],
       [4],
       [8],
       [6],
       [5],
       [5],
       [6],
       [6],
       [6],
       [7]], dtype=int64)

In [83]:
accuracy=clf.score(X_test, y_test)

In [84]:
print(accuracy)

0.571076923076923


In [85]:
#
# Grid Search With Cross Validation using SVC with Train+ Validation and test sets
# Rebuild a model with Training and Validation sets
#

In [86]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100],'gamma': [0.001, 0.01, 0.1, 1, 10, 100]}

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
grid_search = GridSearchCV(SVC(), param_grid, cv=5,return_train_score=True)
grid_search.fit(X_train, y_train)

print("Test set score: {:.2f}".format(grid_search.score(X_test, y_test)))
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}\n".format(grid_search.best_score_))
print("Best estimator:\n{}".format(grid_search.best_estimator_))


KeyboardInterrupt: 

In [ ]:
##
## Analyzing the result of cross-validation
##

In [ ]:
import pandas as pd
# convert to DataFrame
results = pd.DataFrame(grid_search.cv_results_)
# show the first 5 rows
display(results.head())

In [ ]:
results.mean_test_score

In [ ]:
import mglearn
scores = np.array(results.mean_test_score).reshape(6, 6)

# plot the mean cross-validation scores
mglearn.tools.heatmap(scores, 
                      xlabel='gamma',
                      xticklabels=param_grid['gamma'],
                      ylabel='C',
                      yticklabels=param_grid['C'],
                      cmap="viridis")
display

In [ ]:
X_mul = np.array(df.drop(columns=['quality']))

In [ ]:
y_mul = np.array(df.quality)

In [ ]:
from sklearn.preprocessing import label_binarize
y_mul = label_binarize(y_mul, classes=[0, 1, 2, 3])

In [ ]:
np.unique(y_mul)

# Using evaluation metrics in model selection

In [ ]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [107]:
# default scoring for classification is accuracy
print("Default scoring: {}".format(cross_val_score(SVC(), X, y)))
# providing scoring="accuracy" doesn't change the results
explicit_accuracy =  cross_val_score(SVC(), X, y,scoring="accuracy")
print("Explicit accuracy scoring: {}".format(explicit_accuracy)) 
roc_auc = cross_val_score(SVC(), X, y ,scoring=None)
print("AUC scoring: {}".format(roc_auc))

Default scoring: [0.56319188 0.56740536 0.55293574]
Explicit accuracy scoring: [0.56319188 0.56740536 0.55293574]
AUC scoring: [0.56319188 0.56740536 0.55293574]


In [112]:
X_train, X_test, y_train, y_test = train_test_split( X, y, random_state=0)

# we provide a somewhat bad grid to illustrate the point:
param_grid = {'gamma': [0.0001, 0.01, 0.1, 1, 10]}
# using the default scoring of accuracy:
grid = GridSearchCV(SVC(), param_grid=param_grid,cv=5)
grid.fit(X_train, y_train)
print("Grid-Search with accuracy")
print("Best parameters:", grid.best_params_)
print("Best cross-validation score (accuracy): {:.3f}".format(grid.best_score_))
print("Test set AUC: {:.3f}".format(roc_auc_score(y_test.reshape(-1,1), grid.decision_function(X_test))))
print("Test set accuracy: {:.3f}".format(grid.score(X_test, y_test)))

Grid-Search with accuracy
Best parameters: {'gamma': 1}
Best cross-validation score (accuracy): 0.564


ValueError: multiclass format is not supported

In [ ]:
y

In [110]:
grid.decision_function(X_test)

array([[ 0.68360864,  2.95346978,  5.3337017 , ...,  4.20313742,
         1.91841062, -0.47887681],
       [ 0.68328337,  2.95618211,  5.33193701, ...,  4.20691946,
         1.91640431, -0.47893483],
       [ 0.68365073,  2.95376868,  5.33470919, ...,  4.20042154,
         1.9186731 , -0.47886956],
       ...,
       [ 0.68364867,  2.95375404,  5.33493248, ...,  4.20035609,
         1.91865961, -0.47886993],
       [ 0.68365063,  2.95376802,  5.33470615, ...,  4.20043743,
         1.91867252, -0.47886958],
       [ 0.68362377,  2.95357143,  5.33308204, ...,  4.19953418,
         1.91849108, -0.47887408]])

In [111]:
y_test

array([6, 6, 7, ..., 6, 6, 6], dtype=int64)

In [ ]:
# using AUC scoring instead:
grid = GridSearchCV(SVC(), param_grid=param_grid, scoring="roc_auc") 
grid.fit(X_train, y_train)
print("\nGrid-Search with AUC")
print("Best parameters:", grid.best_params_)
print("Best cross-validation score (AUC): {:.3f}".format(grid.best_score_))
print("Test set AUC: {:.3f}".format(
    roc_auc_score(y_test, grid.decision_function(X_test))))
print("Test set accuracy: {:.3f}".format(grid.score(X_test, y_test)))