In [40]:
########################################################################################################################
#   Homework 2                                                                                                         #
#   Due Date: 01.11.2018                                                                                               #
#   Author: Jyothi Nandikonda                                                                                          #
########################################################################################################################

In [41]:
import pandas as pd
import numpy as np

In [42]:
df = pd.read_csv('abalone.data', names=['Sex', 'Length', 'Diameter', 'Height', 'Whole', 'Shucked', 'Viscera', 'Shell', 'Rings'])

In [43]:
del df['Rings']
df.head(2)

Sex  Length  Diameter  Height   Whole  Shucked  Viscera  Shell
0   M   0.455     0.365   0.095  0.5140   0.2245   0.1010   0.15
1   M   0.350     0.265   0.090  0.2255   0.0995   0.0485   0.07

In [44]:
################################################################################################33333333
# PART 1
###############################################################################################
#Take Abalone dataset.
#Run some clustering method (except k-means) with different number of clusters.
#Which number of clusters is better? - use "score"
#
#
#
#

In [45]:
df.replace({"M":0, "F":1, "I":2}, inplace=True)

In [46]:
df.head()

Sex  Length  Diameter  Height   Whole  Shucked  Viscera  Shell
0    0   0.455     0.365   0.095  0.5140   0.2245   0.1010  0.150
1    0   0.350     0.265   0.090  0.2255   0.0995   0.0485  0.070
2    1   0.530     0.420   0.135  0.6770   0.2565   0.1415  0.210
3    0   0.440     0.365   0.125  0.5160   0.2155   0.1140  0.155
4    2   0.330     0.255   0.080  0.2050   0.0895   0.0395  0.055

In [47]:
################PART 1 of HOMEWORK 2#################################

from sklearn import mixture
#from hmmlearn import hmm


In [48]:
g = mixture.GaussianMixture(n_components=20)

In [49]:
g.fit(df) 

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=100,
        means_init=None, n_components=20, n_init=1, precisions_init=None,
        random_state=None, reg_covar=1e-06, tol=0.001, verbose=0,
        verbose_interval=10, warm_start=False, weights_init=None)

In [50]:
g.predict_proba(df)[1]

array([0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.99, 0.  , 0.  , 0.  ])

In [51]:
g.score(df)

20.04496224202629

In [52]:
###########################################################################################333
#      Part2
###########################################################################################
#Take Abalone dataset. Reduce it’s dimensionality to 3 with Kernel PCA, then run clustering with 10 clusters. 
#Q.What age have the cluster centriods?
#
#-Don’t forget to apply feature normalisation before clustering,
#and inverse feature normalisation for the cluster centres!
########################################################################################

In [53]:
X_df = pd.read_csv('abalone.data', names=['Sex', 'Length', 'Diameter', 'Height', 'Whole', 'Shucked', 'Viscera', 'Shell', 'Rings'])

In [54]:
X_df.replace({"M":0,"F":1,"I":2}, inplace=True)

In [55]:
X_df.head()

Sex  Length  Diameter  Height   Whole  Shucked  Viscera  Shell  Rings
0    0   0.455     0.365   0.095  0.5140   0.2245   0.1010  0.150     15
1    0   0.350     0.265   0.090  0.2255   0.0995   0.0485  0.070      7
2    1   0.530     0.420   0.135  0.6770   0.2565   0.1415  0.210      9
3    0   0.440     0.365   0.125  0.5160   0.2155   0.1140  0.155     10
4    2   0.330     0.255   0.080  0.2050   0.0895   0.0395  0.055      7

In [56]:
from sklearn.decomposition import KernelPCA

In [57]:
from sklearn.preprocessing import StandardScaler

scl = StandardScaler()
scl.fit(X_df)
X_df_scaled = scl.transform(X_df)

pca = KernelPCA(n_components=3, kernel="rbf", fit_inverse_transform=True)
pca.fit(X_df_scaled)

KernelPCA(alpha=1.0, coef0=1, copy_X=True, degree=3, eigen_solver='auto',
     fit_inverse_transform=True, gamma=None, kernel='rbf',
     kernel_params=None, max_iter=None, n_components=3, n_jobs=1,
     random_state=None, remove_zero_eig=False, tol=0)

In [58]:
X_df_scaled

array([[-1.15, -0.57, -0.43, ..., -0.73, -0.64,  1.57],
       [-1.15, -1.45, -1.44, ..., -1.21, -1.21, -0.91],
       [ 0.05,  0.05,  0.12, ..., -0.36, -0.21, -0.29],
       ...,
       [-1.15,  0.63,  0.68, ...,  0.98,  0.5 , -0.29],
       [ 0.05,  0.84,  0.78, ...,  0.73,  0.41,  0.02],
       [-1.15,  1.55,  1.48, ...,  1.79,  1.84,  0.64]])

In [59]:
def my_pca(X_input):
    X_scaled = scl.transform(X_input)
    X_out = pca.transform(X_scaled)
    return X_out

In [60]:
Z = my_pca(X_df)

In [61]:
Z

array([[ 0.15, -0.19, -0.43],
       [ 0.47,  0.18, -0.45],
       [ 0.11, -0.53,  0.05],
       ...,
       [-0.53,  0.13, -0.06],
       [-0.52, -0.08,  0.2 ],
       [-0.28,  0.59,  0.05]])

In [62]:
def inverse_pca(X_prediction):
    X_scaled = pca.inverse_transform(X_prediction)
    X_original = scl.inverse_transform(X_scaled)
    return X_original

In [63]:
kpca = my_pca(X_df)

kpca_inv = inverse_pca(kpca)

In [64]:
new_X_df = pd.DataFrame(data=kpca_inv, columns=X_df.columns, index=X_df.index)

In [65]:
new_X_df.head()

Sex    Length  Diameter    Height     Whole   Shucked   Viscera  \
0 -0.048603  0.464142  0.361198  0.127831  0.580318  0.226955  0.122204   
1  0.336334  0.312373  0.235406  0.081081  0.100313  0.031382  0.020752   
2  1.070447  0.516205  0.401965  0.134113  0.658059  0.287123  0.147949   
3 -0.092332  0.465371  0.360977  0.120927  0.493091  0.209280  0.111342   
4  2.043688  0.312690  0.231998  0.074390  0.106876  0.053142  0.024172   

      Shell      Rings  
0  0.185444  11.931521  
1  0.042554   8.130939  
2  0.190281   9.175037  
3  0.147055   9.409214  
4  0.030390   5.379546

In [66]:
X_df.head()

Sex  Length  Diameter  Height   Whole  Shucked  Viscera  Shell  Rings
0    0   0.455     0.365   0.095  0.5140   0.2245   0.1010  0.150     15
1    0   0.350     0.265   0.090  0.2255   0.0995   0.0485  0.070      7
2    1   0.530     0.420   0.135  0.6770   0.2565   0.1415  0.210      9
3    0   0.440     0.365   0.125  0.5160   0.2155   0.1140  0.155     10
4    2   0.330     0.255   0.080  0.2050   0.0895   0.0395  0.055      7

In [67]:
Z

array([[ 0.15, -0.19, -0.43],
       [ 0.47,  0.18, -0.45],
       [ 0.11, -0.53,  0.05],
       ...,
       [-0.53,  0.13, -0.06],
       [-0.52, -0.08,  0.2 ],
       [-0.28,  0.59,  0.05]])

In [68]:
from sklearn.cluster import KMeans

In [69]:
kmeans = KMeans(n_clusters=10, init='k-means++', max_iter=300, n_init=10, random_state=0)

In [70]:
clusters = kmeans.fit_predict(Z)

In [71]:
clusters

array([6, 7, 3, ..., 2, 0, 9])

In [72]:
#10 centers with 3Dimentions
kmeans.cluster_centers_

array([[-0.35, -0.22,  0.18],
       [ 0.63, -0.01,  0.22],
       [-0.54,  0.18,  0.06],
       [ 0.08, -0.43,  0.01],
       [ 0.59,  0.43, -0.11],
       [ 0.22, -0.34,  0.42],
       [-0.01, -0.39, -0.4 ],
       [ 0.44, -0.09, -0.33],
       [-0.38, -0.17, -0.21],
       [-0.34,  0.48,  0.06]])

In [73]:
centers = kmeans.cluster_centers_

In [74]:
inverse1 = pca.inverse_transform(centers)
inverse1.shape

(10, 9)

In [75]:
inverse2 = scl.inverse_transform(inverse1)
inverse2.shape

(10, 9)

In [76]:
X_df.head()

Sex  Length  Diameter  Height   Whole  Shucked  Viscera  Shell  Rings
0    0   0.455     0.365   0.095  0.5140   0.2245   0.1010  0.150     15
1    0   0.350     0.265   0.090  0.2255   0.0995   0.0485  0.070      7
2    1   0.530     0.420   0.135  0.6770   0.2565   0.1415  0.210      9
3    0   0.440     0.365   0.125  0.5160   0.2155   0.1140  0.155     10
4    2   0.330     0.255   0.080  0.2050   0.0895   0.0395  0.055      7

In [77]:
X_centers = pd.DataFrame(data=inverse2, columns=X_df.columns)
X_centers

Sex    Length  Diameter    Height     Whole   Shucked   Viscera  \
0  1.215606  0.588692  0.461416  0.157566  1.004512  0.437222  0.219890   
1  2.011686  0.450142  0.344274  0.114024  0.437061  0.191878  0.091514   
2  0.481443  0.640473  0.504717  0.175592  1.307327  0.570049  0.287387   
3  1.023890  0.521732  0.407340  0.139993  0.715973  0.300734  0.156724   
4  1.808544  0.321237  0.240565  0.081484  0.221796  0.094740  0.046804   
5  2.021624  0.529564  0.409531  0.137020  0.701723  0.308870  0.149148   
6 -0.002623  0.514364  0.401469  0.136633  0.698866  0.292777  0.152998   
7  0.453088  0.400044  0.308015  0.107131  0.320164  0.123738  0.069314   
8  0.040578  0.576559  0.452785  0.156908  0.990171  0.418232  0.212318   
9  0.611624  0.660904  0.521961  0.188274  1.620781  0.696963  0.351274   

      Shell      Rings  
0  0.288558  10.751601  
1  0.130558   8.402665  
2  0.368256  11.633930  
3  0.213429  10.756320  
4  0.067793   6.682559  
5  0.209382   9.614786  
6  0.208346  10.713912  
7  0.105236   9.874226  
8  0.291698  12.112387  
9  0.459187  13.058251

In [78]:
#Age of cluster centroids is Rings+1.5
X_centers['Age'] = X_centers.Rings + 1.5


In [79]:
age_cluster_Centroids = X_centers.Age

In [80]:
age_cluster_Centroids

0    12.251601
1     9.902665
2    13.133930
3    12.256320
4     8.182559
5    11.114786
6    12.213912
7    11.374226
8    13.612387
9    14.558251
Name: Age, dtype: float64

In [81]:
#######################################################################33
#Part 3
#############################################################################3
#Label propagation: -cluster Abalone dataset without age (rings) feature using Gaussian Mixture Model
#-take randomly 20 samples with age from the original Abalone dataset,
#-predict their probabilities with GaussianMM ("predict_proba")
#-compute class distribution for each Gaussian component 
#-compute Gaussian components for each original data point
#-compute labels of original data points by multiplying their Gaussian components by class distribution of these components
#-How correct was this label propagation?
############################################################################3

In [82]:
np.set_printoptions(suppress=True, precision=2)

In [83]:
filename = 'abalone.data'

In [84]:
df = pd.DataFrame()

In [85]:
names = [ 'Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight', 'Viscera weight', 'Shell weight', 'Rings']

In [86]:
df = pd.read_csv(filename ,names = names, delimiter=',')
del df['Rings']

In [87]:
df.head()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell weight  
0         0.150  
1         0.070  
2         0.210  
3         0.155  
4         0.055

In [88]:
replace_list = {"Sex" : {"M": 0, "F" : 1, "I": 2}}
df.replace(replace_list,inplace=True)

In [89]:
df.head()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0    0   0.455     0.365   0.095        0.5140          0.2245   
1    0   0.350     0.265   0.090        0.2255          0.0995   
2    1   0.530     0.420   0.135        0.6770          0.2565   
3    0   0.440     0.365   0.125        0.5160          0.2155   
4    2   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  
0          0.1010         0.150  
1          0.0485         0.070  
2          0.1415         0.210  
3          0.1140         0.155  
4          0.0395         0.055

In [90]:
from sklearn import cluster, datasets, mixture

In [91]:
#Cluster into 7 clusters using Gaussian Mixture Model
g = mixture.GaussianMixture(n_components=7)

In [92]:
x = df.iloc[:,:8].values

In [93]:
x

array([[0.  , 0.46, 0.36, ..., 0.22, 0.1 , 0.15],
       [0.  , 0.35, 0.27, ..., 0.1 , 0.05, 0.07],
       [1.  , 0.53, 0.42, ..., 0.26, 0.14, 0.21],
       ...,
       [0.  , 0.6 , 0.47, ..., 0.53, 0.29, 0.31],
       [1.  , 0.62, 0.48, ..., 0.53, 0.26, 0.3 ],
       [0.  , 0.71, 0.56, ..., 0.95, 0.38, 0.49]])

In [94]:
g.fit(x)

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=100,
        means_init=None, n_components=7, n_init=1, precisions_init=None,
        random_state=None, reg_covar=1e-06, tol=0.001, verbose=0,
        verbose_interval=10, warm_start=False, weights_init=None)

In [95]:
g.predict(x)

array([4, 4, 3, ..., 2, 5, 1], dtype=int64)

In [96]:
x[563]

array([1.  , 0.55, 0.41, 0.15, 0.73, 0.28, 0.16, 0.22])

In [97]:
##############################################################################333
#
# Take 20 Random Samples
#
##############################################################################3

In [98]:
df_small = pd.read_csv(filename ,names = names, delimiter=',').sample(20)
df_small.head()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2746   I   0.485     0.365   0.140        0.4475          0.1895   
3610   M   0.580     0.450   0.160        0.8675          0.3935   
3828   M   0.680     0.520   0.175        1.5430          0.7525   
1071   I   0.385     0.290   0.080        0.2485          0.1220   
1681   F   0.620     0.540   0.165        1.1390          0.4995   

      Viscera weight  Shell weight  Rings  
2746          0.0925        0.2305      8  
3610          0.2210        0.2150      9  
3828          0.3510        0.3740     11  
1071          0.0495        0.0650      7  
1681          0.2435        0.3570     11

In [99]:
replace_list = {"Sex" : {"M": 0, "F" : 1, "I": 2}}
df_small.replace(replace_list,inplace=True)

In [100]:
df_small

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
2746    2   0.485     0.365   0.140        0.4475          0.1895   
3610    0   0.580     0.450   0.160        0.8675          0.3935   
3828    0   0.680     0.520   0.175        1.5430          0.7525   
1071    2   0.385     0.290   0.080        0.2485          0.1220   
1681    1   0.620     0.540   0.165        1.1390          0.4995   
3864    2   0.320     0.235   0.065        0.1385          0.0580   
2473    1   0.615     0.470   0.175        1.2985          0.5135   
3699    0   0.650     0.525   0.190        1.3685          0.5975   
2235    0   0.600     0.480   0.175        1.2290          0.4125   
933     2   0.450     0.360   0.130        0.4780          0.1910   
3273    1   0.475     0.375   0.140        0.5010          0.1920   
908     2   0.335     0.250   0.075        0.1825          0.0705   
1523    0   0.690     0.525   0.200        1.7825          0.9165   
2612    1   0.635     0.495   0.180        1.5960          0.6170   
1999    2   0.350     0.250   0.070        0.1605          0.0715   
1810    0   0.645     0.500   0.160        1.3815          0.6720   
2872    2   0.400     0.315   0.090        0.3245          0.1510   
909     2   0.335     0.250   0.075        0.1860          0.0945   
3023    2   0.470     0.375   0.125        0.5225          0.2265   
3102    0   0.600     0.465   0.180        1.1930          0.5145   

      Viscera weight  Shell weight  Rings  
2746          0.0925        0.2305      8  
3610          0.2210        0.2150      9  
3828          0.3510        0.3740     11  
1071          0.0495        0.0650      7  
1681          0.2435        0.3570     11  
3864          0.0225        0.0500      5  
2473          0.3430        0.3200     14  
3699          0.2960        0.4000     11  
2235          0.2735        0.4150     13  
933           0.1270        0.1370      7  
3273          0.1175        0.1750     13  
908           0.0440        0.0550      7  
1523          0.3325        0.4610     12  
2612          0.3170        0.3700     11  
1999          0.0335        0.0460      6  
1810          0.3260        0.3150      9  
2872          0.0730        0.0880      8  
909           0.0380        0.0445      7  
3023          0.1040        0.1620      8  
3102          0.3150        0.3055      8

In [101]:
proba_small = g.predict_proba(df_small.iloc[:,:-1])
proba_small.shape

(20, 7)

In [102]:
df_small['Rings']

2746     8
3610     9
3828    11
1071     7
1681    11
3864     5
2473    14
3699    11
2235    13
933      7
3273    13
908      7
1523    12
2612    11
1999     6
1810     9
2872     8
909      7
3023     8
3102     8
Name: Rings, dtype: int64

In [103]:
proba_small

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.  ],
       [0.  , 0.01, 0.99, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.01, 0.99, 0.  , 0.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.04, 0.  , 0.96, 0.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.11, 0.89, 0.  , 0.  , 0.  , 0.  ],
       [0.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.86],
       [0.  , 0.  , 0.  , 0.99, 0.  , 0.01, 0.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.97, 0.03, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.01, 0.99, 0.  , 0.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.91, 0.  , 0.  , 0.  , 0.  , 0.  , 0.09],
       [0.  , 0.02, 0.98, 0.  ,

In [104]:
g.predict_proba(x)[563]

array([0.  , 0.  , 0.  , 0.68, 0.  , 0.32, 0.  ])

In [105]:
clusters_small = g.predict_proba(df_small.iloc[:,:8])
rings_small = df_small['Rings']

In [106]:
g.score(x)

19.08481740841179

In [107]:
clusters_small[2]

array([0.  , 0.01, 0.99, 0.  , 0.  , 0.  , 0.  ])

In [108]:
pd.get_dummies(rings_small).head()

5   6   7   8   9   11  12  13  14
2746   0   0   0   1   0   0   0   0   0
3610   0   0   0   0   1   0   0   0   0
3828   0   0   0   0   0   1   0   0   0
1071   0   0   1   0   0   0   0   0   0
1681   0   0   0   0   0   1   0   0   0

In [109]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

In [110]:
pd.get_dummies(df_small['Rings']).head()

5   6   7   8   9   11  12  13  14
2746   0   0   0   1   0   0   0   0   0
3610   0   0   0   0   1   0   0   0   0
3828   0   0   0   0   0   1   0   0   0
1071   0   0   1   0   0   0   0   0   0
1681   0   0   0   0   0   1   0   0   0

In [111]:
cluster_age = proba_small.T @ pd.get_dummies(df_small['Rings'])
cluster_age

array([[1.   , 1.   , 3.136, 1.906, 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.015, 0.018, 0.017, 0.973, 0.115, 0.   ],
       [0.   , 0.   , 0.   , 0.985, 1.982, 1.983, 0.027, 0.885, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.041, 0.   , 0.987, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 1.959, 0.   , 0.013, 1.   ],
       [0.   , 0.   , 0.864, 1.094, 0.   , 0.   , 0.   , 0.   , 0.   ]])

In [112]:
cluster_age = cluster_age / cluster_age.sum(1)[:,None]
cluster_age

array([[0.142, 0.142, 0.445, 0.271, 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.013, 0.016, 0.015, 0.854, 0.101, 0.   ],
       [0.   , 0.   , 0.   , 0.168, 0.338, 0.338, 0.005, 0.151, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.039, 0.   , 0.961, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.659, 0.   , 0.004, 0.336],
       [0.   , 0.   , 0.441, 0.559, 0.   , 0.   , 0.   , 0.   , 0.   ]])

In [ ]:
################################################################################3333
#
# Gaussia components for each data point
#
###############################################################################

In [116]:
predicted_clusters = g.predict_proba(x)
predicted_clusters[:2]  # (point @ component) * (component @ rings)  =  (point @ rings)

array([[0.   , 0.   , 0.184, 0.   , 0.816, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   ]])

In [117]:
predicted_classes = predicted_clusters @ cluster_age
predicted_classes.shape

(4177, 9)

In [118]:
predicted_classes[:3]

array([[0.   , 0.   , 0.   , 0.031, 0.878, 0.062, 0.001, 0.028, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.207, 0.   , 0.702, 0.091]])

In [ ]:
###########################################################################3333
#
# Compute Labels
#
#
#################################################################################

In [119]:
ring_labels = np.array(pd.get_dummies(df_small['Rings']).columns)
ring_labels

array([ 5,  6,  7,  8,  9, 11, 12, 13, 14], dtype=int64)

In [120]:
predicted_rings_easy = ring_labels[predicted_classes.argmax(axis=1)]
predicted_rings_easy

array([ 9,  9, 13, ..., 11, 11, 12], dtype=int64)

In [121]:
predicted_rings_better = predicted_classes @ ring_labels
predicted_rings_better

array([ 9.208,  9.   , 12.676, ..., 10.356, 12.208, 11.91 ])