In [ ]:
##################################################################################################################3333
#
#                         COURSE: 2
#                         Course Name: Machine Learning for Predictive Problems
#                         Student Name: Jyothi Nandikonda
#                         Homework: 1
#                         Due Date: 02.11.18
#
##########################################################################################################################3

Download the two different datasets (for white and red wines): https://archive.ics.uci.edu/ml/datasets/Wine+Quality. Create a new column for the type of wine (eg. 1 for red and 0 for white). Fuse them into one dataset (hint: Use pandas). Tasks:

Use regression to predict the alcohol level of the wine.
Use binary classification to predict the type of wine.
Use multiclass classification to predict the quality of the wine.
For each task test two classifiers, report accuracy with the default parameters. Perform some manual optimization of the parameters (at least 5 different values for each parameter) and plot the new obtained accuracy as a function of the chosen parameter (max. 2). Using your best result, plot the feature importance for the binary classification or the coefficient magnitudes for regression (hint: choose your classifier accordingly).

You can work in small groups but you should submit your notebook individually.

In [3]:
import pandas as pd
import numpy as np

In [4]:
df_white_wine = pd.read_csv('winequality-white.csv', sep=';')

In [5]:
df_red_wine = pd.read_csv('winequality-red.csv', sep=';')

In [6]:
df_red_wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [7]:
df_white_wine["wine_type"] = 0
df_red_wine["wine_type"] = 1

In [8]:
len(df_white_wine)

4898

In [9]:
len(df_red_wine)

1599

In [10]:
df = pd.concat([df_red_wine, df_white_wine], ignore_index=True, sort=True)

In [11]:
df.head()

alcohol  chlorides  citric acid  density  fixed acidity  \
0      9.4      0.076         0.00   0.9978            7.4   
1      9.8      0.098         0.00   0.9968            7.8   
2      9.8      0.092         0.04   0.9970            7.8   
3      9.8      0.075         0.56   0.9980           11.2   
4      9.4      0.076         0.00   0.9978            7.4   

   free sulfur dioxide    pH  quality  residual sugar  sulphates  \
0                 11.0  3.51        5             1.9       0.56   
1                 25.0  3.20        5             2.6       0.68   
2                 15.0  3.26        5             2.3       0.65   
3                 17.0  3.16        6             1.9       0.58   
4                 11.0  3.51        5             1.9       0.56   

   total sulfur dioxide  volatile acidity  wine_type  
0                  34.0              0.70          1  
1                  67.0              0.88          1  
2                  54.0              0.76          1  
3                  60.0              0.28          1  
4                  34.0              0.70          1

In [12]:
df.tail()

alcohol  chlorides  citric acid  density  fixed acidity  \
6492     11.2      0.039         0.29  0.99114            6.2   
6493      9.6      0.047         0.36  0.99490            6.6   
6494      9.4      0.041         0.19  0.99254            6.5   
6495     12.8      0.022         0.30  0.98869            5.5   
6496     11.8      0.020         0.38  0.98941            6.0   

      free sulfur dioxide    pH  quality  residual sugar  sulphates  \
6492                 24.0  3.27        6             1.6       0.50   
6493                 57.0  3.15        5             8.0       0.46   
6494                 30.0  2.99        6             1.2       0.46   
6495                 20.0  3.34        7             1.1       0.38   
6496                 22.0  3.26        6             0.8       0.32   

      total sulfur dioxide  volatile acidity  wine_type  
6492                  92.0              0.21          0  
6493                 168.0              0.32          0  
6494                 111.0              0.24          0  
6495                 110.0              0.29          0  
6496                  98.0              0.21          0

In [13]:
len(df)

6497

In [14]:
from sklearn.utils import shuffle
df = shuffle(df)

In [15]:
df.head()

alcohol  chlorides  citric acid  density  fixed acidity  \
2320     10.4      0.046         0.44  0.99455            6.0   
1905      9.9      0.058         0.24  0.99500            7.2   
2472      9.6      0.037         0.47  0.99390           10.3   
2078     10.4      0.041         0.33  0.99280            6.3   
3594      8.9      0.055         0.38  1.00040            8.4   

      free sulfur dioxide    pH  quality  residual sugar  sulphates  \
2320                 15.0  3.50        5             1.5       0.52   
1905                 40.0  3.20        5             6.7       0.41   
2472                  5.0  2.89        3             1.4       0.28   
2078                 67.0  3.32        6             1.7       0.56   
3594                 51.0  3.34        6            11.8       0.82   

      total sulfur dioxide  volatile acidity  wine_type  
2320                 182.0              0.30          0  
1905                 163.0              0.43          0  
2472                  33.0              0.17          0  
2078                 164.0              0.22          0  
3594                 170.0              0.20          0

In [16]:
df.reset_index(drop=True, inplace=True)

In [17]:
df.dropna()

alcohol  chlorides  citric acid  density  fixed acidity  \
0        10.4      0.046         0.44  0.99455            6.0   
1         9.9      0.058         0.24  0.99500            7.2   
2         9.6      0.037         0.47  0.99390           10.3   
3        10.4      0.041         0.33  0.99280            6.3   
4         8.9      0.055         0.38  1.00040            8.4   
5        11.1      0.030         0.25  0.99120            6.2   
6         9.5      0.073         0.02  0.99680            7.8   
7        11.4      0.036         0.33  0.99058            6.7   
8        12.3      0.074         0.46  0.99649            9.7   
9         8.7      0.056         0.40  0.99670            7.9   
10       11.3      0.031         0.24  0.99480            7.7   
11       11.9      0.036         0.39  0.99000            6.5   
12       10.1      0.050         0.40  0.99510            8.1   
13       10.7      0.030         0.27  0.99388            6.2   
14       10.3      0.060         0.29  0.99572            7.7   
15       12.0      0.031         0.38  0.98956            6.2   
16       11.0      0.076         0.33  0.99599            8.2   
17        8.5      0.034         0.30  0.99642            6.3   
18       12.4      0.093         0.48  0.99408            8.3   
19       12.1      0.026         0.39  0.99286            6.8   
20       12.1      0.030         0.26  0.98894            6.1   
21       11.8      0.109         0.40  0.99614            8.8   
22       10.4      0.056         0.57  0.99464            5.6   
23       10.9      0.039         0.28  0.99406            6.8   
24        9.5      0.041         0.26  0.99410            6.5   
25       10.1      0.084         0.31  0.99824            6.8   
26        9.5      0.078         0.24  0.99830            7.5   
27       11.2      0.044         0.32  0.99644            7.1   
28        9.4      0.157         0.48  0.99760            8.1   
29       10.0      0.081         0.10  0.99830            8.3   
...       ...        ...          ...      ...            ...   
6467     12.0      0.039         0.33  0.99008            6.5   
6468      9.5      0.044         0.35  0.99700            8.0   
6469     11.8      0.034         0.49  0.99580            7.6   
6470      9.5      0.079         0.34  0.99800            9.8   
6471     10.9      0.041         0.28  0.99418            6.5   
6472     10.0      0.038         0.39  0.99400            7.6   
6473     12.1      0.034         0.23  0.98871            5.8   
6474      9.8      0.041         0.22  0.99570            6.2   
6475      9.3      0.053         0.56  0.99810            6.6   
6476      9.1      0.034         0.22  0.99675            6.6   
6477      9.5      0.055         0.46  0.99880            8.7   
6478     12.6      0.029         0.28  0.99060            7.6   
6479      8.9      0.042         0.17  0.99590            6.9   
6480      9.4      0.083         0.00  0.99768            7.1   
6481     11.5      0.121         0.66  0.99780           11.6   
6482     12.8      0.025         0.29  0.99162            7.0   
6483     12.0      0.045         0.50  0.99040            7.8   
6484     10.6      0.044         0.30  0.99460            6.8   
6485     11.0      0.040         0.34  0.99634            7.7   
6486     11.3      0.031         0.25  0.99241            5.0   
6487      9.5      0.076         0.04  0.99745            7.2   
6488     10.4      0.035         0.30  0.99540            7.0   
6489     12.4      0.028         0.36  0.99272            7.3   
6490     10.7      0.060         0.34  0.99310            7.5   
6491      8.8      0.049         0.23  0.99754            6.6   
6492      9.4      0.033         0.17  0.99754            6.9   
6493      9.8      0.078         0.31  0.99800            8.5   
6494     11.9      0.046         0.30  0.99620            6.3   
6495     10.7      0.044         0.28  0.99200            5.8   
6496     10.3      0.243         0.18  0.

In [18]:
df.tail()

alcohol  chlorides  citric acid  density  fixed acidity  \
6492      9.4      0.033         0.17  0.99754            6.9   
6493      9.8      0.078         0.31  0.99800            8.5   
6494     11.9      0.046         0.30  0.99620            6.3   
6495     10.7      0.044         0.28  0.99200            5.8   
6496     10.3      0.243         0.18  0.99612            6.9   

      free sulfur dioxide    pH  quality  residual sugar  sulphates  \
6492                 59.0  3.08        5           12.90       0.49   
6493                 32.0  3.33        5            2.25       0.54   
6494                 49.0  3.74        6           10.00       0.55   
6495                 52.0  3.35        7            4.20       0.44   
6496                  5.5  3.40        6            2.40       0.60   

      total sulfur dioxide  volatile acidity  wine_type  
6492                 186.0             0.400          0  
6493                  58.0             0.460          1  
6494                 212.0             0.310          0  
6495                 158.0             0.280          0  
6496                  48.0             0.765          1

# Using regression to predict the alcohol level of the wine.

Prepring dependent and independent variables for regression

In [19]:
X = np.array(df.drop(columns=['alcohol']))

In [20]:
y = np.array(df.alcohol)

In [21]:
y = y.reshape(-1, 1)

In [22]:
from sklearn import preprocessing

In [23]:
scaler = preprocessing.StandardScaler().fit(y)

In [24]:
X = scaler.transform(X)
y = scaler.transform(y)

In [25]:
X

array([[ -8.75870035,  -8.42833526,  -7.96335059, ..., 143.80792332,
         -8.54572388,  -8.7972709 ],
       [ -8.74863847,  -8.59603328,  -7.96297327, ..., 127.87661183,
         -8.43672016,  -8.7972709 ],
       [ -8.76624677,  -8.40318056,  -7.96389561, ...,  18.87290168,
         -8.65472759,  -8.7972709 ],
       ...,
       [ -8.75870035,  -8.54572388,  -7.96196708, ..., 168.96262566,
         -8.53733897,  -8.7972709 ],
       [ -8.76037734,  -8.56249368,  -7.96548874, ..., 123.68416144,
         -8.56249368,  -8.7972709 ],
       [ -8.59351781,  -8.64634268,  -7.96203416, ...,  31.45025285,
         -8.15582599,  -7.95878082]])

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [28]:
len(X_train)

4872

In [29]:
len(X_test)

1625

In [30]:
linear = LinearRegression()

In [31]:
linear.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [32]:
linear.score(X_test, y_test)

0.8462625092278473

In [33]:
forecast_set = linear.predict(X_test)

In [34]:
#First 5 predictions
forecast_set[: 5]

array([[ 1.33238907],
       [-0.48564943],
       [ 0.25643479],
       [ 1.19224427],
       [-0.45919073]])

In [35]:
#Actual values
y_test[: 5]

array([[ 1.68385508],
       [-0.91546416],
       [-0.07697409],
       [ 1.26461004],
       [-0.49621913]])

In [36]:
y_test_inv = scaler.inverse_transform(y_test)
forecast_set_inv = scaler.inverse_transform(forecast_set)

In [37]:
#First 10 predicted alcohol levels
forecast_set_inv[: 10]

array([[12.08083463],
       [ 9.91260562],
       [10.79763008],
       [11.91369514],
       [ 9.94416081],
       [10.70266846],
       [ 9.65501082],
       [ 9.92436774],
       [11.98300614],
       [ 9.56010583]])

In [38]:
#First 10 actual alcohol levels
y_test_inv[: 10]

array([[12.5],
       [ 9.4],
       [10.4],
       [12. ],
       [ 9.9],
       [ 9.6],
       [ 9.5],
       [ 9.9],
       [12. ],
       [10.1]])

# Binary classification to predict the type of wine.

In [39]:
from sklearn.utils import shuffle
df = shuffle(df)

In [40]:
df.reset_index(drop=True, inplace=True)

In [41]:
df.head()

alcohol  chlorides  citric acid  density  fixed acidity  \
0      9.5      0.053         0.37   0.9992            6.9   
1     12.4      0.035         0.32   0.9906            6.6   
2      9.4      0.080         0.42   0.9974            8.3   
3     10.3      0.031         0.49   0.9932            8.5   
4     11.9      0.033         0.26   0.9903            6.1   

   free sulfur dioxide    pH  quality  residual sugar  sulphates  \
0                 59.0  3.37        7            15.0       0.82   
1                 49.0  3.35        8             1.4       0.64   
2                 11.0  3.21        6             2.0       0.80   
3                 17.0  3.03        6             1.5       0.40   
4                 61.0  3.19        7             1.7       0.81   

   total sulfur dioxide  volatile acidity  wine_type  
0                 178.0              0.22          0  
1                 186.0              0.16          0  
2                  27.0              0.26          1  
3                 122.0              0.15          0  
4                 134.0              0.24          0

In [42]:
X = np.array(df.drop(columns=['wine_type']))

In [43]:
y = np.array(df.wine_type)

In [44]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [45]:
y = y.reshape(-1,1)

In [46]:
y

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [47]:
from sklearn import preprocessing

In [48]:
scaler = preprocessing.StandardScaler().fit(y)

C:\Users\jnandikonda\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [49]:
X = scaler.transform(X)

In [50]:
y

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [53]:
X_train

array([[ 2.54300654e+01, -2.76528923e-01,  1.01884775e-01, ...,
         1.10015404e+00,  3.65735363e+01,  5.42980497e-01],
       [ 2.14834195e+01, -4.55288768e-01,  1.25100340e-01, ...,
         2.87609290e-01,  3.52305211e+02, -1.99917561e-01],
       [ 2.28763534e+01, -3.85642075e-01,  4.26902675e-01, ...,
         7.51920576e-01,  1.94439374e+02,  1.80822875e+00],
       ...,
       [ 2.03226413e+01, -3.46175616e-01, -5.71366589e-01, ...,
         7.75136140e-01,  8.76477777e+01,  8.91213961e-01],
       [ 2.54300654e+01, -4.39037873e-01,  4.03687111e-01, ...,
         1.03050735e+00,  6.90753263e+01, -1.30270868e-01],
       [ 2.26441977e+01, -4.39037873e-01,  1.94747032e-01, ...,
         7.05489447e-01,  2.94266300e+02,  3.22380824e-02]])

In [54]:
from sklearn import svm

In [55]:
clf = svm.SVC()

In [56]:
clf.fit(X_train, y_train)

C:\Users\jnandikonda\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [57]:
clf.score(X_test, y_test)

0.8726153846153846

In [58]:
forecast_set = clf.predict(X_test)

In [59]:
forecast_set[: 10]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [60]:
actual_set = y_test

In [61]:
actual_set[: 10]

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1]], dtype=int64)

# Multiclass classification to predict the quality of the wine.

In [62]:
from sklearn.utils import shuffle
df = shuffle(df)

In [63]:
df.reset_index(drop=True, inplace=True)

In [64]:
df.shape

(6497, 13)

In [65]:
X = np.array(df.drop(columns=['quality']))

In [66]:
y = np.array(df.quality)

In [67]:
np.unique(df.quality)

array([3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [68]:
le = preprocessing.LabelEncoder()

In [69]:
le.fit_transform(y)

array([3, 3, 2, ..., 3, 2, 3], dtype=int64)

In [70]:
np.unique(y)

array([3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [71]:
y = y.reshape(-1, 1)

In [72]:
y

array([[6],
       [6],
       [5],
       ...,
       [6],
       [5],
       [6]], dtype=int64)

In [73]:
scaler_multiclass = preprocessing.StandardScaler().fit(y)

C:\Users\jnandikonda\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [74]:
X = scaler_multiclass.transform(X)

In [75]:
X

array([[  4.67439084,  -6.61298287,  -6.35416119, ..., 112.44040807,
         -6.53739778,  -6.66337293],
       [  6.8503253 ,  -6.59465921,  -6.20528147, ...,  16.24120034,
         -6.06785403,  -5.51814427],
       [  3.52916217,  -6.62558039,  -6.17092461, ..., 256.73921967,
         -6.36561348,  -6.66337293],
       ...,
       [  6.96484816,  -6.62099947,  -6.30835205, ...,  20.82211499,
         -6.23963833,  -6.66337293],
       [  4.21629937,  -6.6141281 ,  -6.36561348, ..., 146.79726797,
         -6.26826904,  -6.66337293],
       [  6.5067567 ,  -6.61756379,  -6.31980433, ...,  91.82629213,
         -6.35416119,  -6.66337293]])

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [77]:
clf = svm.SVC()

In [78]:
clf.fit(X_train, y_train)

C:\Users\jnandikonda\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [79]:
clf.score(X_test, y_test)

0.5661538461538461

In [80]:
forecast_set = clf.predict(X_test)

In [81]:
forecast_set[: 10].reshape(-1, 1)

array([[5],
       [6],
       [5],
       [6],
       [5],
       [7],
       [5],
       [6],
       [5],
       [6]], dtype=int64)

In [82]:
actual_set = y_test

In [83]:
actual_set[: 10]

array([[5],
       [5],
       [5],
       [6],
       [6],
       [7],
       [5],
       [7],
       [5],
       [7]], dtype=int64)