In [1]:
import pandas as pd 
import datetime as dt
import numpy as np

In [2]:
pd.core.common.is_list_like = pd.api.types.is_list_like
from pandas_datareader.data import DataReader

In [3]:
#Define dateframe for stock we retrieve
end = dt.datetime.now()
start = end - dt.timedelta(days=5*365)


df = DataReader('AAPL', 'iex', start, end)
df.head(3)

5y


open     high      low    close    volume
date                                                    
2013-09-30  62.4263  63.0031  62.0549  62.3609  64852879
2013-10-01  62.5832  63.9815  62.5742  63.8272  88255013
2013-10-02  63.5224  64.3295  63.2765  64.0365  71849680

In [4]:
df['Log_Ret'] = np.log(df["close"] / df["close"].shift(1))

In [5]:
df.tail(2)

open    high     low   close    volume   Log_Ret
date                                                          
2018-09-25  219.75  222.82  219.70  222.19  24554379  0.006321
2018-09-26  221.00  223.75  219.76  220.42  23984706 -0.007998

In [6]:
df['Log_Ret'].quantile(0.25)

-0.005858253311365566

In [7]:
df['Crash'] = np.where((df['Log_Ret'] < df['Log_Ret'].quantile(0.25)), '1','0')

In [8]:
df['Down'] = np.where(((df['Log_Ret'] < df['Log_Ret'].quantile(0.50)) & (df['Log_Ret'] > df['Log_Ret'].quantile(0.25))), '1','0')

In [9]:
df['Up'] = np.where(((df['Log_Ret'] > df['Log_Ret'].quantile(0.50)) & (df['Log_Ret'] < df['Log_Ret'].quantile(0.75))), '1','0')

In [10]:
df['Jump'] = np.where((df['Log_Ret'] > df['Log_Ret'].quantile(0.75)), '1','0')

In [11]:
df.head(2)

open     high      low    close    volume   Log_Ret Crash Down  \
date                                                                            
2013-09-30  62.4263  63.0031  62.0549  62.3609  64852879       NaN     0    0   
2013-10-01  62.5832  63.9815  62.5742  63.8272  88255013  0.023241     0    0   

           Up Jump  
date                
2013-09-30  0    0  
2013-10-01  0    1

In [12]:
df.head(20)

open     high      low    close     volume   Log_Ret Crash  \
date                                                                        
2013-09-30  62.4263  63.0031  62.0549  62.3609   64852879       NaN     0   
2013-10-01  62.5832  63.9815  62.5742  63.8272   88255013  0.023241     0   
2013-10-02  63.5224  64.3295  63.2765  64.0365   71849680  0.003274     0   
2013-10-03  64.1607  64.4014  62.8826  63.2320   80629248 -0.012643     1   
2013-10-04  63.2909  63.3877  62.6029  63.1823   64673329 -0.000786     0   
2013-10-07  63.6441  64.4407  63.4858  63.7997   77919884  0.009724     0   
2013-10-08  64.0862  64.1777  62.8566  62.9089   72418815 -0.014061     1   
2013-10-09  63.3929  63.8050  62.5610  63.6477   75311488  0.011676     0   
2013-10-10  64.2667  64.4053  63.7068  64.0467   69650490  0.006249     0   
2013-10-11  63.7003  64.5963  63.4609  64.4619   66934938  0.006462     0   
2013-10-14  64.0718  65.0855  64.0090  64.8841   65474542  0.006528     0   
2013-10-15  65.0757  65.6637  64.8161  65.2294   80018603  0.005308     0   
2013-10-16  65.5054  65.7330  65.3014  65.5478   62775013  0.004869     0   
2013-10-17  65.3995  66.0273  65.3602  65.9907   63398335  0.006734     0   
2013-10-18  66.1856  66.6133  66.1490  66.5649   72635570  0.008664     0   
2013-10-21  66.9416  68.5806  66.9089  68.1963   99526945  0.024213     0   
2013-10-22  68.8560  69.1234  66.4524  68.0008  133515753 -0.002871     0   
2013-10-23  67.8873  68.7598  67.8873  68.6669   78431122  0.009748     0   
2013-10-24  68.6722  69.6493  68.3386  69.5760   96191095  0.013152     0   
2013-10-25  69.4982  69.7487  68.6866  68.7975   84448133 -0.011252     1   

           Down Up Jump  
date                     
2013-09-30    0  0    0  
2013-10-01    0  0    1  
2013-10-02    0  1    0  
2013-10-03    0  0    0  
2013-10-04    1  0    0  
2013-10-07    0  0    1  
2013-10-08    0  0    0  
2013-10-09    0  0    1  
2013-10-10    0  1    0  
2013-10-11    0  1    0  
2013-10-14    0  1    0  
2013-10-15    0  1    0  
2013-10-16    0  1    0  
2013-10-17    0  1    0  
2013-10-18    0  0    1  
2013-10-21    0  0    1  
2013-10-22    1  0    0  
2013-10-23    0  0    1  
2013-10-24    0  0    1  
2013-10-25    0  0    0

In [13]:
df["moving_average3"] = df["close"].rolling(3).mean()

In [14]:
df["moving_average14"] = df["close"].rolling(14).mean()

In [15]:
df["moving_average21"] = df["close"].rolling(21).mean()

In [16]:
df.reset_index(inplace=True)

In [17]:
df.head(22)

date     open     high      low    close     volume   Log_Ret Crash  \
0   2013-09-30  62.4263  63.0031  62.0549  62.3609   64852879       NaN     0   
1   2013-10-01  62.5832  63.9815  62.5742  63.8272   88255013  0.023241     0   
2   2013-10-02  63.5224  64.3295  63.2765  64.0365   71849680  0.003274     0   
3   2013-10-03  64.1607  64.4014  62.8826  63.2320   80629248 -0.012643     1   
4   2013-10-04  63.2909  63.3877  62.6029  63.1823   64673329 -0.000786     0   
5   2013-10-07  63.6441  64.4407  63.4858  63.7997   77919884  0.009724     0   
6   2013-10-08  64.0862  64.1777  62.8566  62.9089   72418815 -0.014061     1   
7   2013-10-09  63.3929  63.8050  62.5610  63.6477   75311488  0.011676     0   
8   2013-10-10  64.2667  64.4053  63.7068  64.0467   69650490  0.006249     0   
9   2013-10-11  63.7003  64.5963  63.4609  64.4619   66934938  0.006462     0   
10  2013-10-14  64.0718  65.0855  64.0090  64.8841   65474542  0.006528     0   
11  2013-10-15  65.0757  65.6637  64.8161  65.2294   80018603  0.005308     0   
12  2013-10-16  65.5054  65.7330  65.3014  65.5478   62775013  0.004869     0   
13  2013-10-17  65.3995  66.0273  65.3602  65.9907   63398335  0.006734     0   
14  2013-10-18  66.1856  66.6133  66.1490  66.5649   72635570  0.008664     0   
15  2013-10-21  66.9416  68.5806  66.9089  68.1963   99526945  0.024213     0   
16  2013-10-22  68.8560  69.1234  66.4524  68.0008  133515753 -0.002871     0   
17  2013-10-23  67.8873  68.7598  67.8873  68.6669   78431122  0.009748     0   
18  2013-10-24  68.6722  69.6493  68.3386  69.5760   96191095  0.013152     0   
19  2013-10-25  69.4982  69.7487  68.6866  68.7975   84448133 -0.011252     1   
20  2013-10-28  69.2006  69.4570  68.4380  69.3100  137610123  0.007422     0   
21  2013-10-29  70.1463  70.5361  67.3040  67.5836  158952115 -0.025224     1   

   Down Up Jump  moving_average3  moving_average14  moving_average21  
0     0  0    0              NaN               NaN               NaN  
1     0  0    1              NaN               NaN               NaN  
2     0  1    0        63.408200               NaN               NaN  
3     0  0    0        63.698567               NaN               NaN  
4     1  0    0        63.483600               NaN               NaN  
5     0  0    1        63.404667               NaN               NaN  
6     0  0    0        63.296967               NaN               NaN  
7     0  0    1        63.452100               NaN               NaN  
8     0  1    0        63.534433               NaN               NaN  
9     0  1    0        64.052100               NaN               NaN  
10    0  1    0        64.464233               NaN               NaN  
11    0  1    0        64.858467               NaN               NaN  
12    0  1    0        65.220433               NaN               NaN  
13    0  1    0        65.589300         64.082557               NaN  
14    0  0    1        66.034467         64.382843               NaN  
15    0  0    1        66.917300         64.694921               NaN  
16    1  0    0        67.587333         64.978086               NaN  
17    0  0    1        68.288000         65.366293               NaN  
18    0  0    1        68.747900         65.822986               NaN  
19    0  0    0        69.013467         66.179971               NaN  
20    0  1    0        69.227833         66.637193         65.536581  
21    0  0    0        68.563700         66.918329         65.785281

In [18]:

import plotly.plotly as py
from plotly.offline import iplot
import plotly.graph_objs as go

In [19]:
data = [go.Scatter(x=df.date, y=df['moving_average3'])]

py.iplot(data)

PlotlyRequestError: Account limit reached: Your account is limited to creating 25 charts. To continue, you can override or delete existing charts or you can upgrade your account at: https://plot.ly/products/cloud

In [20]:
#plot for close and moving average3 

trace1 = go.Scatter(
    x=df.date,
    y=df['close']
)
trace2 = go.Scatter(
    x=df.date,
    y=df['moving_average3']
)
data = [trace1, trace2]

py.iplot(data)

PlotlyRequestError: Account limit reached: Your account is limited to creating 25 charts. To continue, you can override or delete existing charts or you can upgrade your account at: https://plot.ly/products/cloud

In [21]:
trace = go.Ohlc(open=df.open,
               high=df.high,
               low=df.low,
               close=df.close)
data=[trace]
py.iplot([trace], filename='simple_ohlc')

In [22]:
#Moving avereage for Log_ret
df["log_ret_MA"] = df["Log_Ret"].rolling(100).mean()



In [23]:
df.head(50)

date     open     high      low    close     volume   Log_Ret Crash  \
0   2013-09-30  62.4263  63.0031  62.0549  62.3609   64852879       NaN     0   
1   2013-10-01  62.5832  63.9815  62.5742  63.8272   88255013  0.023241     0   
2   2013-10-02  63.5224  64.3295  63.2765  64.0365   71849680  0.003274     0   
3   2013-10-03  64.1607  64.4014  62.8826  63.2320   80629248 -0.012643     1   
4   2013-10-04  63.2909  63.3877  62.6029  63.1823   64673329 -0.000786     0   
5   2013-10-07  63.6441  64.4407  63.4858  63.7997   77919884  0.009724     0   
6   2013-10-08  64.0862  64.1777  62.8566  62.9089   72418815 -0.014061     1   
7   2013-10-09  63.3929  63.8050  62.5610  63.6477   75311488  0.011676     0   
8   2013-10-10  64.2667  64.4053  63.7068  64.0467   69650490  0.006249     0   
9   2013-10-11  63.7003  64.5963  63.4609  64.4619   66934938  0.006462     0   
10  2013-10-14  64.0718  65.0855  64.0090  64.8841   65474542  0.006528     0   
11  2013-10-15  65.0757  65.6637  64.8161  65.2294   80018603  0.005308     0   
12  2013-10-16  65.5054  65.7330  65.3014  65.5478   62775013  0.004869     0   
13  2013-10-17  65.3995  66.0273  65.3602  65.9907   63398335  0.006734     0   
14  2013-10-18  66.1856  66.6133  66.1490  66.5649   72635570  0.008664     0   
15  2013-10-21  66.9416  68.5806  66.9089  68.1963   99526945  0.024213     0   
16  2013-10-22  68.8560  69.1234  66.4524  68.0008  133515753 -0.002871     0   
17  2013-10-23  67.8873  68.7598  67.8873  68.6669   78431122  0.009748     0   
18  2013-10-24  68.6722  69.6493  68.3386  69.5760   96191095  0.013152     0   
19  2013-10-25  69.4982  69.7487  68.6866  68.7975   84448133 -0.011252     1   
20  2013-10-28  69.2006  69.4570  68.4380  69.3100  137610123  0.007422     0   
21  2013-10-29  70.1463  70.5361  67.3040  67.5836  158952115 -0.025224     1   
22  2013-10-30  67.9671  69.0018  67.6284  68.6586   88540697  0.015781     0   
23  2013-10-31  68.6722  68.9979  68.1843  68.3716   68923785 -0.004189     0   
24  2013-11-01  68.5440  68.6460  67.4740  68.0221   68722304 -0.005125     0   
25  2013-11-04  68.1620  68.9102  67.8625  68.9011   61157033  0.012839     0   
26  2013-11-05  68.6172  69.1804  68.4106  68.7309   66368071 -0.002473     0   
27  2013-11-06  68.9613  69.0547  68.1785  68.5363   55844152 -0.002835     0   
28  2013-11-07  68.3600  68.8350  67.4128  67.4275   65655100 -0.016311     1   
29  2013-11-08  67.7022  68.5640  67.4404  68.4890   69829543  0.015620     0   
30  2013-11-11  68.4140  68.6350  67.6798  68.2901   56863303 -0.002908     0   
31  2013-11-12  68.1088  68.9311  68.0206  68.4166   51114651  0.001851     0   
32  2013-11-13  68.1522  68.7113  68.0153  68.4987   49304927  0.001199     0   
33  2013-11-14  68.7850  69.6363  68.6613  69.4889   70605087  0.014352     0   
34  2013-11-15  69.2810  69.6113  69.0060  69.0720   79479764 -0.006018     1   
35  2013-11-18  69.0718  69.3613  68.1785  68.2349   61236224 -0.012193     1   
36  2013-11-19  68.2877  68.8600  68.1482  68.3561   52234707  0.001775     0   
37  2013-11-20  68.3140  68.4706  67.6693  67.7575   48545798 -0.008796     1   
38  2013-11-21  68.0995  68.5745  67.5825  68.5648   65506861  0.011844     0   
39  2013-11-22  68.3522  68.6995  68.2219  68.3890   55931232 -0.002567     0   
40  2013-11-25  68.5495  69.1876  68.5469  68.9074   57348403  0.007552     0   
41  2013-11-26  68.9574  70.5388  68.9416  70.1783  100345728  0.018276     0   
42  2013-11-27  70.5612  71.8361  70.1783  71.8308   90861841  0.023274     0   
43  2013-11-29  72.2939  73.4583  72.0742  73.1610   79532215  0.018349     0   
44  2013-12-02  73.4149  74.2477  72.4702  72.5242  118135885 -0.008742     1   
45  2013-12-03  73.4544  74.5174  73.3728  74.5098  112741734  0.027010     0   
46  2013-12-04  74.4016  74.8871  73.7859  74.3359   94452666 -0.002337     0   
47  2013-12-05  75.3424  75.6694  74.5214  74.7175  111895315  0.005120     0   
48  2013-12-06  74.4398  74.5661  73.6214

In [24]:
trace1 = go.Scatter(
    x=df.date,
    y=df['close']
)
trace2 = go.Scatter(
    x=df.date,
    y=df['log_ret_MA']
)
data = [trace1, trace2]

py.iplot(data)

PlotlyRequestError: Account limit reached: Your account is limited to creating 25 charts. To continue, you can override or delete existing charts or you can upgrade your account at: https://plot.ly/products/cloud

In [25]:
df['Label'] = df["close"].shift(-1)

In [26]:
df.head(5)

date     open     high      low    close    volume   Log_Ret Crash  \
0  2013-09-30  62.4263  63.0031  62.0549  62.3609  64852879       NaN     0   
1  2013-10-01  62.5832  63.9815  62.5742  63.8272  88255013  0.023241     0   
2  2013-10-02  63.5224  64.3295  63.2765  64.0365  71849680  0.003274     0   
3  2013-10-03  64.1607  64.4014  62.8826  63.2320  80629248 -0.012643     1   
4  2013-10-04  63.2909  63.3877  62.6029  63.1823  64673329 -0.000786     0   

  Down Up Jump  moving_average3  moving_average14  moving_average21  \
0    0  0    0              NaN               NaN               NaN   
1    0  0    1              NaN               NaN               NaN   
2    0  1    0        63.408200               NaN               NaN   
3    0  0    0        63.698567               NaN               NaN   
4    1  0    0        63.483600               NaN               NaN   

   log_ret_MA    Label  
0         NaN  63.8272  
1         NaN  64.0365  
2         NaN  63.2320  
3         NaN  63.1823  
4         NaN  63.7997

In [27]:
df.dtypes

date                 object
open                float64
high                float64
low                 float64
close               float64
volume                int64
Log_Ret             float64
Crash                object
Down                 object
Up                   object
Jump                 object
moving_average3     float64
moving_average14    float64
moving_average21    float64
log_ret_MA          float64
Label               float64
dtype: object

In [28]:
df.head(5)

date     open     high      low    close    volume   Log_Ret Crash  \
0  2013-09-30  62.4263  63.0031  62.0549  62.3609  64852879       NaN     0   
1  2013-10-01  62.5832  63.9815  62.5742  63.8272  88255013  0.023241     0   
2  2013-10-02  63.5224  64.3295  63.2765  64.0365  71849680  0.003274     0   
3  2013-10-03  64.1607  64.4014  62.8826  63.2320  80629248 -0.012643     1   
4  2013-10-04  63.2909  63.3877  62.6029  63.1823  64673329 -0.000786     0   

  Down Up Jump  moving_average3  moving_average14  moving_average21  \
0    0  0    0              NaN               NaN               NaN   
1    0  0    1              NaN               NaN               NaN   
2    0  1    0        63.408200               NaN               NaN   
3    0  0    0        63.698567               NaN               NaN   
4    1  0    0        63.483600               NaN               NaN   

   log_ret_MA    Label  
0         NaN  63.8272  
1         NaN  64.0365  
2         NaN  63.2320  
3         NaN  63.1823  
4         NaN  63.7997

In [29]:
df.drop(columns=['date','moving_average3', 'moving_average14', 'moving_average21'], inplace=True)

In [30]:
df.dropna(inplace=True)

In [31]:
df.head(5)

open     high      low    close    volume   Log_Ret Crash Down Up  \
100  69.2417  70.1378  69.1451  69.8241  72364950  0.004369     0    0  1   
101  70.0663  70.0908  68.9572  69.0975  58247350 -0.010461     1    0  0   
102  69.3026  69.4866  68.2425  68.4741  69131286 -0.009063     1    0  0   
103  68.4463  69.9869  68.3020  69.8400  75557321  0.019751     0    0  0   
104  70.0266  70.5123  69.1054  69.6507  93074653 -0.002714     0    1  0   

    Jump  log_ret_MA    Label  
100    0    0.001130  69.0975  
101    0    0.000793  68.4741  
102    0    0.000670  69.8400  
103    1    0.000994  69.6507  
104    0    0.000975  69.8519

In [32]:
from sklearn import model_selection
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression, ElasticNet, ridge
from sklearn.neural_network import MLPClassifier

In [33]:
len(df)

1157

In [34]:
import numpy as np

In [35]:
X = np.array(df.drop(['Label'], 1))

In [36]:
X

array([[69.2417, 70.1378, 69.1451, ..., '1', '0', 0.0011304074596805297],
       [70.0663, 70.0908, 68.9572, ..., '0', '0', 0.0007933911888370296],
       [69.3026, 69.4866, 68.2425, ..., '0', '0', 0.0006700233828643872],
       ...,
       [220.78, 221.36, 217.29, ..., '0', '0', 0.002597931904489951],
       [216.82, 221.26, 216.63, ..., '0', '1', 0.0023084387332855043],
       [219.75, 222.82, 219.7, ..., '1', '0', 0.0023535437317916946]],
      dtype=object)

In [37]:
y = np.array(df['Label'])

In [38]:
y

array([ 69.0975,  68.4741,  69.84  , ..., 220.79  , 222.19  , 220.42  ])

In [39]:
y = y.reshape(-1,1)

In [40]:
y

array([[ 69.0975],
       [ 68.4741],
       [ 69.84  ],
       ...,
       [220.79  ],
       [222.19  ],
       [220.42  ]])

In [41]:
scaler = preprocessing.StandardScaler().fit(y)

In [42]:
X = scaler.transform(X)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning:

Data with input dtype object was converted to float64 by StandardScaler.



In [43]:
X

array([[-1.56389183, -1.53881062, -1.5665956 , ..., -3.47392931,
        -3.50191861, -3.50188698],
       [-1.54081185, -1.54012612, -1.57185479, ..., -3.50191861,
        -3.50191861, -3.50189641],
       [-1.56218728, -1.55703725, -1.59185874, ..., -3.50191861,
        -3.50191861, -3.50189986],
       ...,
       [ 2.67755926,  2.69379305,  2.5798766 , ..., -3.50191861,
        -3.50191861, -3.5018459 ],
       [ 2.56672163,  2.69099412,  2.56140366, ..., -3.50191861,
        -3.47392931, -3.501854  ],
       [ 2.64873028,  2.73465743,  2.64733081, ..., -3.47392931,
        -3.50191861, -3.50185274]])

In [44]:
y = scaler.transform(y)

In [45]:
y

array([[-1.56792789],
       [-1.58537642],
       [-1.54714583],
       ...,
       [ 2.67783915],
       [ 2.71702417],
       [ 2.66748311]])

In [46]:
from sklearn.model_selection import TimeSeriesSplit

In [48]:
tscv = TimeSeriesSplit(n_splits=5)

In [49]:
for train_index, test_index in tscv.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [50]:
X_train

array([[-1.56389183, -1.53881062, -1.5665956 , ..., -3.47392931,
        -3.50191861, -3.50188698],
       [-1.54081185, -1.54012612, -1.57185479, ..., -3.50191861,
        -3.50191861, -3.50189641],
       [-1.56218728, -1.55703725, -1.59185874, ..., -3.50191861,
        -3.50191861, -3.50189986],
       ...,
       [ 1.30268561,  1.3176291 ,  1.27031038, ..., -3.50191861,
        -3.47392931, -3.5018814 ],
       [ 1.33727479,  1.40147385,  1.3367234 , ..., -3.50191861,
        -3.47392931, -3.50187215],
       [ 1.3414256 ,  1.35138979,  1.31541514, ..., -3.50191861,
        -3.50191861, -3.50187317]])

In [51]:
len(X_train)

965

In [54]:
len(X_test)

192

In [55]:
linear = LinearRegression()

In [56]:
linear.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [57]:
linear.score(X_test, y_test)

0.9801631300564994

In [59]:
linear.predict(np.array([[69.3026,69.4866,68.2425,68.4741,69131286,-0.009063,1,0,0,0,0.000670]]))

array([[69.28275873]])

In [ ]:
scaler = preprocessing.StandardScaler().fit(y)

In [ ]:
X = scaler.transform(X)

In [ ]:
y = scaler.transform(y)

In [ ]:
y

In [ ]:
from sklearn.model_selection import TimeSeriesSplit

In [ ]:
tscv = TimeSeriesSplit(n_splits=5)

In [ ]:
for train_index, test_index in tscv.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [ ]:
X_train

In [ ]:
len(X_train)

In [ ]:
len(X_test)

In [ ]:
linear = LinearRegression()

In [ ]:
linear.fit(X_train, y_train)

In [ ]:
linear.score(X_test, y_test)

In [ ]:
mlp = MLPClassifier()

In [ ]:
mlp.fit(X_train, y_train)